# TABU CONSTS
TABU_SIZE = 50
TABU_ITERATIONS = 100
TABU_LIMIT = 50
NUM_OF_CITIES = 40

# GENERAL CONSTS
MAP_X = 200
MAP_Y = 200
PATH_TO_CITIES = './data/cities.json'

# GENETIC CONSTS
SEED = "127dada4"
INITIAL_POPULATION = 50
GENETIC_ITERATIONS = 500
TOURNAMENTS_SELECTION = 1
ROULETTE_SELECTION = 2
