# TABU CONSTS
TABU_SIZE = 15
TABU_ITERATIONS = 100
TABU_LIMIT = TABU_SIZE


# GENERAL CONSTS
MAP_X = 200
MAP_Y = 200
PATH_TO_CITIES = './data/cities.json'
NUM_OF_CITIES = 40

# GENETIC CONSTS
SEED = "as1d6a1da16s5d1"
INITIAL_POPULATION = 50
GENETIC_ITERATIONS = 500
TOURNAMENTS_SELECTION = 1
ROULETTE_SELECTION = 2
